sudo: required
services: 
  - docker

before_install:
  - docker build -t ronaldoveras/docker/client  -f Dockerfile.dev .

script:
  - docker run ronaldoveras/docker/client npm run test -- --coverage
